# Generated by Django 4.1.1 on 2022-09-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0002_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
