# Generated by Django 4.1.1 on 2022-09-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0003_user_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
